openapi: "3.0.0"
info:
  version: 0.1.0
  title: Simple server
  license:
    name: MIT
servers:
  - url: http://localhost/
paths:
  /pet/{id}:
    get:
      summary: Get a pet by ID
      operationId: getPet
      parameters:
        - name: id
          in: path
          description: Pet ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetNotFoundResponse'
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      parameters:
        - name: tag
          in: query
          description: Only return pets with these tags
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        200:
          description: 'Looking good!'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
    PetNotFoundResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
        joke:
          type: string
